185 add new words
omen273/crosswordApp pull request #191
Opened 2021-05-15 14:51 UTC by greenEkatherine

2021-05-15 19:15 UTC, omen273 commented on app/src/main/res/raw/data.json
> +            "word": "cereal",
Это - каша https://translate.google.ru/?sl=en&tl=ru&text=cereal&op=translate

2021-05-15 19:20 UTC, omen273 commented on app/src/main/res/raw/data.json
> +        "topics": ["приготовление и употребление еды"]
Может просто еда

2021-05-15 19:21 UTC, omen273 commented on app/src/main/res/raw/data.json
> +            "word": "столешница",
Почему это еда?

2021-05-15 19:23 UTC, omen273 commented on app/src/main/res/raw/data.json
> +        "topics": ["приготовление и употребление еды", "еда"]
Здесь видимо должна быть одна тема

2021-05-15 19:31 UTC, omen273 commented on app/src/main/res/raw/data.json
> +        "topics": ["cooking and eating",  "food"]
It is not food in your logic

2021-05-15 19:33 UTC, omen273 commented on app/src/main/res/raw/data.json
> +            "word": "столешница",
Ok I understand, sorry https://ru.wikipedia.org/wiki/%D0%A1%D1%82%D0%BE%D0%BB%D0%B5%D1%88%D0%BD%D0%B8%D1%86%D0%B0

2021-05-15 19:54 UTC, omen273 commented on app/src/main/res/raw/data.json
> +        "topics": ["приготовление и употребление еды"]
Decided to stay as is

2021-05-15 19:54 UTC, omen273 requested changes
Please address my comments

2021-05-16 14:22 UTC, greenEkatherine commented on app/src/main/res/raw/data.json
> +            "word": "cereal",
https://en.wikipedia.org/wiki/Breakfast_cereal не только

2021-05-16 14:24 UTC, greenEkatherine commented on app/src/main/res/raw/data.json
> +        "topics": ["приготовление и употребление еды", "еда"]
я долго думала, но кажется, что имбирь например или лук вполне себе можно есть

2021-05-16 14:36 UTC, greenEkatherine commented on app/src/main/res/raw/data.json
> +            "word": "cereal",
а каша вот https://en.wikipedia.org/wiki/Porridge

2021-05-16 14:39 UTC, greenEkatherine commented
Please check my answers and update

2021-05-16 19:07 UTC, greenEkatherine commented on app/src/main/res/raw/data.json
> +            "word": "cereal",
p. 3 https://www.oxfordlearnersdictionaries.com/definition/english/cereal

2021-05-16 19:13 UTC, greenEkatherine commented on app/src/main/res/raw/data.json
> +            "word": "cereal",
будут зерновые

2021-05-16 19:18 UTC, omen273 approved these changes

2021-05-16 19:18 UTC, merged