185 A2 (animals, food, cooking, music)
omen273/crosswordApp pull request #199
Opened 2021-05-20 19:17 UTC by greenEkatherine

part of #185

2021-05-21 20:59 UTC, omen273 commented on app/src/main/res/raw/data.json
> +            "word": "пикировать",
почему не нырять?

2021-05-21 20:59 UTC, omen273 commented on app/src/main/res/raw/data.json
> +            "word": "вымирание",
Это - гусь

2021-05-21 21:01 UTC, omen273 commented on app/src/main/res/raw/data.json
> +            "topics": ["food"],
Такого перевода нет в гугле

2021-05-21 21:03 UTC, omen273 requested changes
Please address my comments

2021-05-22 11:37 UTC, greenEkatherine commented on app/src/main/res/raw/data.json
> +            "word": "пикировать",
потому что про птиц так тоже говорят

2021-05-22 11:41 UTC, greenEkatherine commented on app/src/main/res/raw/data.json
> +            "topics": ["food"],
modified

2021-05-22 11:41 UTC, greenEkatherine commented on app/src/main/res/raw/data.json
> +            "word": "вымирание",
fixed

2021-05-22 12:33 UTC, omen273 approved these changes

2021-05-22 12:34 UTC, merged