Update data.json
omen273/crosswordApp pull request #201
Opened 2021-06-03 14:28 UTC by Nickelody

[    {"EN":{        "word": "advancement",        "topics": ["science"],	"level": "advanced(C1)"        }},    {"RU": {        "word": "продвижение",        "topics": ["наука"]        }}    ], 	[    {"EN":{        "word": "analyse",        "topics": ["science"],	"level": "intermediate(B1)"        }},    {"RU": {        "word": "анализировть",        "topics": ["наука"]        }}    ],     	[    {"EN":{        "word": "case study",        "topics": ["science"],        "level": "upper-intermediate(B2)"        }},    {"RU": {        "word": "тематическое исследование",        "topics": ["наука"]        }}    ]

2021-06-04 18:14 UTC, greenEkatherine commented on app/src/main/res/raw/data.json
> +        "word": "case study",
please remove because it is 2 words

2021-06-04 18:16 UTC, greenEkatherine commented on app/src/main/res/raw/data.json
>      ]
please add comma here

2021-06-05 09:21 UTC, greenEkatherine commented on app/src/main/res/raw/data.json
> +        "word": "продвижение",
исправь пожалуйста на развитие

2021-06-05 17:48 UTC, omen273 requested changes
Please address my comments

2021-06-05 17:49 UTC, greenEkatherine commented on app/src/main/res/raw/data.json
> +            "word": "кафедра",
discussed offline - кафедра ok

2021-06-05 18:57 UTC, omen273 approved these changes

2021-06-05 18:57 UTC, merged