185 movies A1-B2
omen273/crosswordApp pull request #210
Opened 2021-06-20 13:12 UTC by greenEkatherine

2021-06-23 21:33 UTC, greenEkatherine commented
Json is broken but I cannot find there

2021-06-24 19:24 UTC, greenEkatherine commented
Fixed! 💃

2021-06-26 15:31 UTC, omen273 commented on app/src/main/res/raw/data.json
>              "word": "television",
It is not телевизор.

2021-06-26 15:32 UTC, omen273 commented on app/src/main/res/raw/data.json
> +					"word": "окончание",
конец

2021-06-26 15:33 UTC, omen273 commented on app/src/main/res/raw/data.json
> +					"word": "окончание",
Или концовка

2021-06-26 15:34 UTC, omen273 commented on app/src/main/res/raw/data.json
> +                "word": "экранизировать",
снимать

2021-06-26 15:36 UTC, omen273 commented on app/src/main/res/raw/data.json
> +					"word": "субтитр",
It is better to use plural https://en.wikipedia.org/wiki/Subtitles

2021-06-26 15:52 UTC, omen273 commented on app/src/main/res/raw/data.json
> +					"word": "interval",
перерыв или антракт a short period of time separating parts of a play, film or concert

2021-06-26 15:55 UTC, omen273 commented on app/src/main/res/raw/data.json
> +            "word": "show",
не сеанс a программа

2021-06-26 15:55 UTC, omen273 requested changes
Please address my comments

2021-06-27 08:52 UTC, greenEkatherine commented on app/src/main/res/raw/data.json
> +					"word": "окончание",
употребляется, но я еще уточню

2021-06-27 08:58 UTC, greenEkatherine commented on app/src/main/res/raw/data.json
> +            "word": "show",
обсудили, что можно переименовать movies and TV

2021-06-27 09:26 UTC, greenEkatherine commented on app/src/main/res/raw/data.json
> +					"word": "interval",
выкину, потому что это к театру имеет отношение, а не к кино

2021-06-27 09:29 UTC, greenEkatherine commented on app/src/main/res/raw/data.json
> +            "word": "show",
я бы разделила все-таки, проверила - в теме телевидение хватает слов на все уровни

2021-06-27 09:30 UTC, greenEkatherine commented on app/src/main/res/raw/data.json
> +					"word": "окончание",
заменила на конец

2021-06-27 13:39 UTC, omen273 approved these changes

2021-06-27 13:40 UTC, merged