253: add education B1 and travel A1-B1
omen273/crosswordApp pull request #254
Opened 2021-10-28 19:47 UTC by greenEkatherine

Resolves #253

2021-11-01 13:42 UTC, omen273 commented on app/src/main/res/raw/data.json
>          "word": "коттедж",
Это разное, лучше деревенский дом

2021-11-01 13:52 UTC, omen273 commented on app/src/main/res/raw/data.json
> +        "word": "предпоказ",
Это не совсем то On today’s show, we’ll have exclusive previews of some of the best new music. Если точно, то это дорелизная демонстрация или допремьерная. Но мне тоже не нравится такое определение.

2021-11-01 14:03 UTC, omen273 commented on app/src/main/res/raw/data.json
> +        "word": "движение на дорогах",
Почему не "трафик"?

2021-11-01 14:05 UTC, omen273 commented on app/src/main/res/raw/data.json
> +        "word": "поход",
Это не поход, living in a tent, etc. on holiday это жить в палатках.

2021-11-01 14:06 UTC, omen273 commented on app/src/main/res/raw/data.json
> +        "word": "вагон",
Не американский английский

2021-11-01 14:09 UTC, omen273 commented on app/src/main/res/raw/data.json
> +        "word": "постоялец",
Это все называют гостем. Мне кажется потстоялец устаревшее.

2021-11-01 14:11 UTC, omen273 commented on app/src/main/res/raw/data.json
> +        "word": "экскурсовод",
Я бы сказал гид
Эти слова часто используются как синонимы, однако они имеют некоторые смысловые отличия, установившиеся в практике употребления. Зачастую, говоря «экскурсовод» мы имеем в виду специалиста, проводящего экскурсии в музее. В то время как «гид» — это человек, обычно работающий в турфирме по договору, который проводит несколько экскурсий (обзорную, по некоторым музеям и памятникам) и находится с группой туристов значительное время, обычно сопровождая их на протяжении всего тура
https://ru.wikipedia.org/wiki/%D0%AD%D0%BA%D1%81%D0%BA%D1%83%D1%80%D1%81%D0%BE%D0%B2%D0%BE%D0%B4

2021-11-01 14:19 UTC, omen273 commented on app/src/main/res/raw/data.json
> +        "word": "место",
Это еще походит для топика кино

2021-11-01 14:22 UTC, omen273 commented on app/src/main/res/raw/data.json
> +        "word": "путь",
Может железнодорожный путь

2021-11-01 14:25 UTC, omen273 commented on app/src/main/res/raw/data.json
> +        "word": "автотранспорт",
Нет, это любое транспортное средство с мотором https://en.wikipedia.org/wiki/Vehicle

2021-11-01 14:27 UTC, omen273 commented on app/src/main/res/raw/data.json
> +        "word": "вылет",
Это еще отправление и это лучше

2021-11-01 14:28 UTC, omen273 commented on app/src/main/res/raw/data.json
> +        "word": "переправа",
паром это a boat or ship that carries people, vehicles and goods across a river or across a narrow part of the sea

2021-11-01 14:30 UTC, omen273 requested changes
Please check american english and address my comments in addtion.

2021-11-03 20:01 UTC, greenEkatherine commented on app/src/main/res/raw/data.json
> +        "word": "экскурсовод",
вот бы отзывы на гугл плее так писали

2021-11-03 20:07 UTC, greenEkatherine commented on app/src/main/res/raw/data.json
> +        "word": "постоялец",
в словарях помечено как разговорное, а не устаревшее, но я заменю

2021-11-03 20:13 UTC, greenEkatherine commented on app/src/main/res/raw/data.json
> +        "word": "вагон",
nice catch

2021-11-03 20:22 UTC, greenEkatherine commented on app/src/main/res/raw/data.json
> +        "word": "предпоказ",
можно совсем убрать

2021-11-04 18:35 UTC, greenEkatherine commented on app/src/main/res/raw/data.json
> +        "word": "поход",
удалила

2021-11-04 18:35 UTC, greenEkatherine commented on app/src/main/res/raw/data.json
> +        "word": "предпоказ",
убрала

2021-11-04 19:26 UTC, greenEkatherine commented
> Please check american english and address my comments in addtion.

All done

2021-11-04 21:51 UTC, merged