Work A1-B1
omen273/crosswordApp pull request #265
Opened 2021-11-07 14:05 UTC by greenEkatherine

Resolves #264

2021-11-09 18:58 UTC, omen273 commented on app/src/main/res/raw/data.json
> +        "word": "танцовщик",
Почему не "танцовщица"?

2021-11-09 19:17 UTC, omen273 requested changes
Please address my comments

2021-11-09 19:17 UTC, omen273 commented on app/src/main/res/raw/data.json
> +        "word": "interview",
Я бы только одно оставил

2021-11-09 19:17 UTC, omen273 commented on app/src/main/res/raw/data.json
> +        "word": "трудоустраивать",
Может нанимать

2021-11-09 19:17 UTC, omen273 commented on app/src/main/res/raw/data.json
> +        "word": "маляр",
Там еще художник и декоратор

2021-11-09 19:17 UTC, omen273 commented on app/src/main/res/raw/data.json
> +        "word": "физическая (работа)",
Убери я тему лучше для всех добавлю

2021-11-09 19:17 UTC, omen273 commented on app/src/main/res/raw/data.json
> +        "word": "секретарь приемной",
администратор

2021-11-09 19:17 UTC, omen273 commented on app/src/main/res/raw/data.json
> +        "word": "(ночная) смена",
Убери здесь скобки

2021-11-09 19:17 UTC, omen273 commented on app/src/main/res/raw/data.json
> +    "EN": {
Можно одно оставить

2021-11-10 21:09 UTC, greenEkatherine commented on app/src/main/res/raw/data.json
> +        "word": "(ночная) смена",
ок, добавить "на работе" или ты тему добавишь?

2021-11-10 21:09 UTC, greenEkatherine commented on app/src/main/res/raw/data.json
> +        "word": "танцовщик",
можно и так

2021-11-10 21:19 UTC, greenEkatherine commented on app/src/main/res/raw/data.json
> +    "EN": {
У нас же обучающее приложение, важно знать, что есть и глагол, и существительное

2021-11-10 21:55 UTC, omen273 approved these changes

2021-11-10 21:56 UTC, merged