290: fix review dialog crash
omen273/crosswordApp pull request #310
Opened 2022-02-05 10:56 UTC by greenEkatherine

Fixes #290

2022-02-05 17:17 UTC, omen273 requested changes
Please address my comment

2022-02-05 17:17 UTC, omen273 commented on app/src/main/java/com/omen273/crossLingo/GameActivity.kt
> +            if (number >=0/*== 3 || number % 100 == 0*/) requestReview()
Please return it back

2022-02-05 20:59 UTC, greenEkatherine commented on app/src/main/java/com/omen273/crossLingo/GameActivity.kt
> +            if (number >=0/*== 3 || number % 100 == 0*/) requestReview()
done

2022-02-06 11:57 UTC, omen273 approved these changes

2022-02-06 11:57 UTC, merged